name: Production Deploy
on:
  push:
    branches:
      - production
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js 12
      uses: actions/setup-node@v1
      with:
        node-version: '12'
    - name: Yarn Install
      run: |
        cd frontend && yarn install
    - name: Build
      env:
        TM_APP_BASE_URL: ${{ secrets.PRODUCTION_TM_APP_BASE_URL }}
        TM_APP_API_URL: ${{ secrets.PRODUCTION_TM_APP_API_URL }}
        TM_APP_API_VERSION: ${{ secrets.PRODUCTION_TM_APP_API_VERSION }}
        TM_ORG_NAME: ${{ secrets.PRODUCTION_TM_ORG_NAME }}
        TM_ORG_CODE: ${{ secrets.PRODUCTION_TM_ORG_CODE }}
        TM_ORG_URL: ${{ secrets.PRODUCTION_TM_ORG_URL }}
        TM_ORG_PRIVACY_POLICY_URL: ${{ secrets.PRODUCTION_TM_ORG_PRIVACY_POLICY_URL }}
        TM_ORG_TWITTER: ${{ secrets.PRODUCTION_TM_ORG_TWITTER }}
        TM_ORG_GITHUB: ${{ secrets.PRODUCTION_TM_ORG_GITHUB }}
        TM_CONSUMER_KEY: ${{ secrets.PRODUCTION_TM_CONSUMER_KEY }}
        TM_CONSUMER_SECRET: ${{ secrets.PRODUCTION_TM_CONSUMER_SECRET }}
        OSM_SERVER_URL: ${{ secrets.PRODUCTION_OSM_SERVER_URL }}
        OSM_REGISTER_URL: ${{ secrets.PRODUCTION_OSM_REGISTER_URL }}
        ID_EDITOR_URL: ${{ secrets.PRODUCTION_ID_EDITOR_URL }}
        POTLATCH2_EDITOR_URL: ${{ secrets.PRODUCTION_POTLATCH2_EDITOR_URL }}
        MAP_MAX_AREA: ${{ secrets.MAP_MAX_AREA }}
      run: |
        cd frontend && yarn build
    - name: Unit Tests
      run: |
        cd frontend && yarn test --testPathIgnorePatterns internationalization.test.js 
    - name: Deploy to S3
      uses: jakejarvis/s3-sync-action@master
      with:
        args: --acl public-read --delete
      env:
        AWS_S3_BUCKET: ${{ secrets.AWS_PRODUCTION_BUCKET_NAME }}
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_REGION: ${{ secrets.AWS_REGION }}
        SOURCE_DIR: "frontend/build"
